apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: {{ .Values.app2.servicePort }}
      targetPort: 5001
  type: NodePort
